spring:
  application:
    name: my-eureka-server
server: 
  port: 8762
eureka:
 instance:
    hostname: my-eureka-server-01
    prefer-ip-address: true
 client:
    service-url:
      defaultZone: http://my-eureka-server-02:8763/eureka/
